name: CI for Tests and Package Publishing

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install django_eventstream && pip install pytest && pip install -e ./


      - name: freeze
        run: |
          pip freeze

      - name: Run pytest
        run: |
          pytest